plugins:
  - rubocop-rspec

AllCops:
  Exclude:ß
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

RSpec/ImplicitExpect:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ReturnFromStub:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Max: 8
  AllowSubject: false
