plugins:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable

# Deprecated Cop の置き換え
Naming/PredicatePrefix:
  Enabled: true
