plugins:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "bin/**"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

# Deprecated Cop の置き換え
Naming/PredicatePrefix:
  Enabled: true

# 日本語でも context 警告をださない
RSpec/ContextWording:
  Enabled: false